### ISSUE TITLE
incomplete blastn results used during restarted job

### ISSUE THREAD

**Issue by colinbrislawn** [pnnl/hundo#16]
This is a small-ish issue.

My job timed out in the queue and was canceled. When I restarted it, this happened:

```
rule compute_lca:
    input: OTU.fasta, blast-hits.txt, /pic/projects/mint/hundo/ref/silvamod128.map, /pic/projects/mint/hundo/ref/silvamod128.tre
    output: OTU_tax.fasta, OTU_assignments.tsv
    jobid: 1061


        hundo lca --min-score 125             --top-fraction 0.95             OTU.fasta blast-hits.txt /pic/projects/mint/hundo/ref/silvamod128.map             /pic/projects/mint/hundo/ref/silvamod128.tre OTU_tax.fasta OTU_assignments.tsv
        

rule run_blast:
    input: OTU.fasta, /pic/projects/mint/hundo/ref/silvamod128.fasta.nhr, /pic/projects/mint/hundo/ref/silvamod128.fasta.nin, /pic/projects/mint/hundo/ref/silvamod128.fasta.nsq, /pic/projects/mint/hundo/ref/silvamod128.map, /pic/projects/mint/hundo/ref/silvamod128.tre, /pic/projects/mint/hundo/ref/silvamod128.fasta
    output: blast-hits.txt
    jobid: 1622
    threads: 24
```

😱  compute_lca running before blast?! 

Turns out that the `blast-hits.txt` file was not removed when the job was killed, so snakemake started working with this incomplete file.

The snakemake repo has a [related question](https://bitbucket.org/snakemake/snakemake/issues/485/is-there-an-easy-way-to-remove-incomplete)  about incomplete files.

**Comment by brwnj** [comment]
`hundo` always uses `--rerun-incomplete`, so I'm not certain what else could be done in instances like this. What's your Snakemake version?

**Comment by colinbrislawn** [comment]
I should have read the [related question](https://bitbucket.org/snakemake/snakemake/issues/485/is-there-an-easy-way-to-remove-incomplete) more closely!

>c) --remove-incomplete: i.e. remove the incomplete files from the filesystem and associated snakemake metadata, build a new command (with the new config), and run.

It looks like this method would remove the incomplete blast results, so that compute_lca would run only after blast had finished successfully. Do you think we could use the --remove-incomplete flag?

**Comment by brwnj** [comment]
`--remove-incomplete` was a proposed option and doesn't actually exist. I feel like this is a bug in Snakemake because it still is finding that the output of an incomplete job is 'complete'.

How was `hundo` called? Was `--cluster` used or was everything being executed on a single node? What's your Snakemake version?

**Comment by colinbrislawn** [comment]
I ran `hundo` on an interactive node with the `--no-conda` flag and without `--cluster` flag.

Sounds to me that `--remove-incomplete` might be the setting we want... should I reopen that issue?

**Comment by brwnj** [comment]
Not in my opinion. If Snakemake cannot determine that the file is incomplete in order to re-run the command that generated it (`--rerun-incomplete`), then it likely will also not know to remove it.
