### ISSUE TITLE
Stuck at "Downloading remote packages"

### ISSUE THREAD

**Issue by gabyrech** [pnnl/hundo#19]
Hi! Thanks for this nice soft! I am trying to download the conda environment using this command, but it gets stuck in "Downloading remote packages" 

```
$ hundo annotate --out-dir tmp_out --database-dir annotation_references --reference-database silva tmp --conda-prefix condaEnviroment --create-envs-only

Building DAG of jobs...
Creating conda environment ...envs/hundo_env/lib/python3.6/site-packages/hundo/environment.yml...
Downloading remote packages.
```
Any suggestion?
Thanks!

**Comment by gabyrech** [comment]
No worries, I tried a couple of times and at the end it worked.
Best,
Gabriel

**Comment by colinbrislawn** [comment]
Hello Gabriel,

That `Downloading remote packages` is part of Snakemake, but I wish it was more informative. This is deploying the conda environment needed for this workflow, and that can take awhile.

I can investigate how to improve this message or show a progress indicator, or we can simply close this issue.

**Comment by brwnj** [comment]
This appears to be solved.

**Comment by gabyrech** [comment]
Great! Thanks!
