### ISSUE TITLE
Consider adding vsearch --fastq_eestats

### ISSUE THREAD

**Issue by colinbrislawn** [pnnl/hundo#2]
This function of usearch and vsearch makes a tab separated file that shows the quality across a fastq file. 

Here is what graphs of the output look like:
<img width="788" alt="screen shot 2017-07-12 at 1 38 56 pm" src="https://user-images.githubusercontent.com/10355152/28139010-8e4b4192-6707-11e7-95fd-b0470655dda0.png">

I know similar functionality is currently supported in FQC. Adding this text output would be simple. Adding graphs of this output could elegantly let users see quality, say after joining reads.

**Comment by brwnj** [comment]
For a sample or for all samples (after concatenation)? If for a sample, how do you envision summarizing hundreds or a thousand separate samples? If for all samples, how can the plot be altered to better display metrics on millions or hundreds of millions of reads?

**Comment by colinbrislawn** [comment]
Per-sample variation is already captured by FQC, so running this on concatenated samples from each MiSeq run would would well. 

I think this information would be most useful at the very start and very end of quality control. At the start we need to pick good settings. At the end, we need to see if it worked.
(In this example, we can see that expected error spikes at 220 bp, so more trimming is needed.)

>hundreds of millions of reads

I imagine that this command is pretty fast, but I have not timed it. It takes pipes, so you could simply pipe in all the merged fastq files to get this output. 

The graphs themselves would not have to change as they scale with read length.

**Comment by colinbrislawn** [comment]
> If for a sample, how do you envision summarizing hundreds or a thousand separate samples? 

Trelliscope is perfect for this. 😉 

But that would be overkill. This is most helpful on concatenated samples.

**Comment by colinbrislawn** [comment]
Testing:
`time cat *merged.fastq | vsearch --fastq_eestats - --output all_merged.log`
For compressed files: 
`time zcat *merged.fastq | vsearch --fastq_eestats - --output all_merged.log`
`time cat *merged.fastq | vsearch --fastq_eestats - --gzip_decompress --output all_merged.log`

---

I think this is CPU limited, not disk limited. It does not support multithreading.

|  size | time | speed | file type |
|------|-----|--------|--------|
| 5.5 MB | 1 s | 5.5 MB/s |    |
| 55 MB | 3 s | 18 MB/s |    |
| 546 MB | 24 s | 23 MB/s |    |
| 546 MB | 23 s | 24 MB/s | gz + `zcat` |
| 546 MB | 23 s | 24 MB/s | gz + `--gzip_decompress` |
| 2691 MB | 200 s (3+ min) | 13.5 MB/s |    |
| 3169 MB | 300 s (5 min) | 10.6 MB/s |    |
| 6459 MB | 564 s (9.5 min) | 11.4 MB/s |    |

So it's only a good fit for medium files, like the high-quality, joined fastq files.

**Comment by brwnj** [comment]
I think we'll just go with the error plots on the concatenated file for now. This limits our ability to say everything about the qualities of the raw sequences, but is a good starting point to have something. I think it would be nice to have a trelliscope panel and be able to dig into individual samples, but it adds a lot of requirements and greatly complicates the report generation at the end of the workflow.

**Comment by colinbrislawn** [comment]
I agree. Making this report as the final step before dereplication gives us lots of data for minimum effort.

I think I could get a trelliscope display up and running pretty easily, but adding it to the workflow would be a mess. If we are interested, I could set up a demo and we could see if it's worth it.

**Comment by brwnj** [comment]
I set up a demo to see how large the file size gets when you set `self_contained = TRUE` and it's ugly. For only 30 plots, it was already up to 5 MB and that's without the other tables that are already embedded in the hundo report. If you work on demo, try to test rbokeh options.

**Comment by colinbrislawn** [comment]
Yeah, TrelliscopeJS is heavy at scale; on a different project, I hit 70 MB with 3k rbrokeh plots.

Would you like me to submit a PR for some part of this? I'm not familiar with python graphing, but I could add the rule for report generation.

**Comment by brwnj** [comment]
Should be all set. Here's the example: https://pnnl.github.io/hundo/
