### ISSUE TITLE
update blast so modern libssl is supported

### ISSUE THREAD

**Issue by colinbrislawn** [pnnl/hundo#22]
Error: 
```python
blastdbcmd -db /home/smit684/Tools/hundo/example/annotation_references/silvamod128.fasta -outfmt %f -entry all -out /home/smit684/Tools/hundo/example/annotation_references/silvamod128.fasta
Activating conda environment: /home/smit684/Tools/hundo/example/mothur_sop_silva/.snakemake/conda/2bc5ce0c
blastdbcmd: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

> error while loading shared libraries: libssl.so.1.0.0: 

libssl is no longer on conda as it's old (and old crypto libraries are 🙀). Bumping blast to a newer version should fix this problem.

**Comment by brwnj** [comment]
can you test blast 2.9.0 in a new env to make sure it's working?

**Comment by colinbrislawn** [comment]
I'm testing this with Montana @mslarae13 and it works. I have not compared the results of the blastn search itself, but the commands work as intended.

I've pushed changes to master and bumped the patch version. Can you push a new version to pypy so we can try fresh install?

**Comment by brwnj** [comment]
done.
