### ISSUE TITLE
report downloads

### ISSUE THREAD

**Issue by brwnj** [pnnl/hundo#5]
Zip contents into single file for downloading rather than multiple.

**Comment by colinbrislawn** [comment]
We briefly spoke about having hundo save stdout to a log file and including that in the report. I'm not sure if that's included in this issue, or if that's a separate enhancement.

**Comment by brwnj** [comment]
I'll try to get that into this as we need a way to track omitted samples.

**Comment by brwnj** [comment]
Snakemake captures a log per execution, but you can redirect stdout into stderr and capture everything into an explicit log file like:

```
hundo annotate... 2>&1 | tee log.txt
```
