### ISSUE TITLE
Improve concurrency in initial sample processing

### ISSUE THREAD

**Issue by colinbrislawn** [pnnl/hundo#7]
The hundo pipeline is very amenable to parallelization, as most of the initial steps happen on a per-sample basis. When running on a single machine (laptop or single node) the concurrency of these initial steps is the limiting factor.

Because `--jobs` and `--threads` default to all the cores on the machine, any steps in which the program can use multiple threads defaults to using all threads. There are some exceptions, like `trim_and_filter_reads` and `get_prefilter_fastq_stats` that have been hard-coded to us a single thread, but `trim_and_filter_reads` which uses bbduk2, still runs serially because the algorithm claims to offer full concurrency.

However, the bbduk2 step only uses 4 to 6 cores, so this step greatly reduces concurrency and increases run time. 

On my last few runs, I used `--jobs 36 --threads 12`, and while that's more than what the machine can support and limits speed on later steps, this mitigated the bbduk2 bottleneck and reduced run time from 1.5 hours to about 30 minutes.

Could I submit a PR to set bbduk2 threads through the CLI or hard-code the threads?

Colin

@smcolby reviewed this code with me and discovered that jobs == threads == no concurrency

**Comment by brwnj** [comment]
Would adding a variable, say `subthreads`, suffice? This would work such that rule `trim_and_filter_reads` would set threads as:

```
    threads:
        config.get("subthreads", config.get("threads", 1))
```

**Comment by colinbrislawn** [comment]
Yes, that could work.

The core problem is that some programs don't make use of all the threads they are allocated, and we can improve concuranty by only giving them the threads they will use.

I like the idea of using `threads` for cpu limited program like blast and vsearch and using `subthreads` for non-cpu limited programs like bbduk2 and FastTreeMP. We could also set threads on a per rule basis, but maybe that's overly cumbersome.

Do you think it's worth it to offer granular thread control, or is `subthreads` a good middle ground?

**Comment by brwnj** [comment]
As bbduk is always going to be IO bound in this use case, I just added a fraction multiplier to threads for this rule. It will always be 1/4 of threads (9b3c1a899959cb5af99d12a78fec0c4c301a499f). Concurrency improved; `jobs` still does not equal `threads`.

**Comment by colinbrislawn** [comment]
That's an elegant solution. Thanks Joe.

**Comment by brwnj** [comment]
Sure thing!
